version: '1.29.2'
services:
  node:
    build: .
    container_name: market-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mariadb
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6378:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  mariadb:
    image: "mariadb:latest"
    container_name: mariadb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIA_DB_PASSWORD}
      - MYSQL_USER=${MARIA_DB_USERNAME}
      - MYSQL_PASSWORD=${MARIA_DB_PASSWORD}
volumes:
  db_data:
